POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "data bases",
    "important": false
}

####

POST http://localhost:3001/api/notes
Content-Type: application/json

{
   
}